Depend on homebrew/dupes/zlib, not zlib
Without this change:

  $ brew tap homebrew/dupes
  $ brew install zlib
  $ brew install php56
  ==> Installing php56 from homebrew/homebrew-php
  ==> Downloading https://www.php.net/get/php-5.6.4.tar.bz2/from/this/mirror
  Already downloaded: /Library/Caches/Homebrew/php56-5.6.4
  ==> Patching
  Error: No available formula for dupes/zlib
  Searching formulae...
  Searching taps...

And then it stops.

With this change, it all works.